# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crudfirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crudfirebase
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  target 'crudfirebase-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'crudfirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'crudfirebase-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crudfirebase-tvOS

 

end
